ARDUINO_DIR = /usr/share/arduino
ARDUINO_LIBS = LiquidCrystal/src
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
ARDUINO_CORE_PATH = $(HOME)/.arduino15/packages/arduino/hardware/avr/1.6.2/cores/arduino
BOARDS_TXT =  $(HOME)/.arduino15/packages/arduino/hardware/avr/1.6.2/boards.txt
ARDUINO_VAR_PATH =  $(HOME)/.arduino15/packages/arduino/hardware/avr/1.6.2/variants
BOOTLOADER_PARENT =  $(HOME)/.arduino15/packages/arduino/hardware/avr/1.6.2/bootloaders


BOARD_TAG = mega
MCU = atmega2560
F_CPU = 16000000UL

include /usr/share/arduino/Arduino.mk
